### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#1]
Can y'all make a vector file that I can use to generate the favicon and things like the iphone home screen icons? Thanks!

**Comment by nikkichung** [comment]
On it! I'll add this to our internal to-do list.

**Comment by nikkichung** [comment]
We've begun this but are awaiting color approval before finalizing it.

**Comment by nikkichung** [comment]
@halfempty This is now in the Dropbox. https://www.dropbox.com/s/s1qe52l0ws4qysg/commonedge_favicon.ai?dl=0.

**Comment by halfempty** [comment]
Done!
