### ISSUE TITLE
Newsletter Sign-up

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#10]
MailChimp. @halfempty Do you need us to set up a MailChimp account?

**Comment by halfempty** [comment]
@nikkichung Yes!

**Comment by nikkichung** [comment]
@halfempty MailChimp account has been created.

Login: commedgecollab
Pass: Coming in an email

**Comment by halfempty** [comment]
I've made some initial progress on the Newsletter. The styling at this point is rudimentary, but I'll return to it once I've made some progress on the other high-priority items.
