### ISSUE TITLE
Donation Module

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#11]
Paypal. @halfempty Do you need us to set up a Paypal account?

**Comment by halfempty** [comment]
@nikkichung yes, good idea!

**Comment by nikkichung** [comment]
@halfempty Paypal account is up. 

commonedgedonate@gmail.com
pass coming by email.

**Comment by halfempty** [comment]
I've made some initial progress on the Donation module. The styling at this point is rudimentary, but I'll return to it once I've made some progress on the other high-priority items.
