### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#13]
@halfempty Package of mockups files is in our shared Dropbox
https://www.dropbox.com/sh/ljqwc2tx04dpov7/AAAzMeEj-9C3haw2tXNzkM0Za?dl=0

We designed with the 'Suggested Reading' section in mind, but would like to include a featured (newest) post at the top.

**Comment by halfempty** [comment]
@nikkichung Looks good. Could you add one thing? For many landing pages (other than homepage), we should add a title at the top saying what category / tag / search result we're browsing. Does that make sense? Could you comp how you'd like that styled?

**Comment by Dungjai** [comment]
@halfempty could we wait on this until Monday? @nikkichung is out today. If not, I can try to figure this out. Let me know.

**Comment by halfempty** [comment]
@Dungjai no problem waiting
