### ISSUE TITLE
WP Engine reset

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#14]
Got this from WP Engine:

Hi Martin,

At WP Engine we are committed to providing robust security. We are writing today to let you know that we learned of an exposure involving some of our customers’ credentials. Out of an abundance of caution, we are proactively taking security measures across our entire customer base.

We have begun an investigation, however there is immediate action we are taking. Additionally, there is action that requires your immediate attention.

While we have no evidence that the information was used inappropriately, as a precaution, we are invalidating the following five passwords associated with your WP Engine account. This means you will need to reset each of them. Instructions for how to reset these passwords are at the bottom of this email.

WP Engine User Portal
WordPress Database
SFTP
Original WP-Admin Account
Password Protected Installs and Transferable Installs
As a security best practice we also recommend, if you use this password elsewhere with other applications, that you change and update those passwords as well.

We apologize for any inconvenience this event may have caused. We are taking this exposure as an opportunity to review and enhance our security, and remain committed to strong internal security practices and processes.

We take the security of our customers very seriously. Should you have any questions after resetting your User Portal password, please feel free to contact the WP Engine support team or simply reply to this email. You may also obtain more information about this event by visiting http://wpengine.com/infosec

Sincerely,
The WP Engine Team

Instructions for Resetting Passwords:

User Portal Account – This is the User Portal account that was created when you signed up for WP Engine. Reset this password by using the Forgot Password link. We recommend you do not reset it to the same password you had last.
WordPress Database Password – This is the password WordPress uses to communicate to the database. This will be a seamless reset that will not impact WordPress. If you need these credentials you can find them in the wp-config.php file
SFTP Password – Reset this password from the WP Engine User Portal. We recommend you do not reset it to the same password you had last.
Original WP-Admin Account – This is the WP-Admin account that was created when you first created the install. Reset this password by going to your WP-Admin login page and using the Forgot Password Link. We recommend you do not reset it to the same password you had last.
Password Protected Installs and Transferable Installs – This is the password you use to access any installs, both staging and live, that you have enabled Password Protection on or for your Transferable Installs. To reset this password, go to the Utilities section of the User Portal for the specific install and use the edit icon to change the password.

**Comment by nikkichung** [comment]
Thanks, Marty. We got this for our studio site as well. I'm trying to parse
what the different passwords are—if I can't figure it out I'll holler for
help.

Nikki Chung
Once–Future Office
+1 917 524 8187
http://once-future.com

On Thu, Dec 10, 2015 at 6:54 AM, Marty Spellerberg <notifications@github.com

**Comment by nikkichung** [comment]
@marty We're resetting our individual account passwords. Can you take care of the other ones?

**Comment by halfempty** [comment]
Okay, I think this is all done
