### ISSUE TITLE
Top-nav / logo

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#15]
@halfempty Top-nav design intent is included in the Landing page mock-ups.
- [x] MUST-HAVE We'd like to prioritize having a vertical nav appear at the 1024+ breakpoint that collapses down into the horizontal nav as the user scrolls.

![screenshot 2015-12-10 22 52 39](https://cloud.githubusercontent.com/assets/15950066/11735588/d7c03232-9f90-11e5-85c8-09f11c5031f8.png)

![screenshot 2015-12-10 22 53 46](https://cloud.githubusercontent.com/assets/15950066/11735592/e9c5dfd6-9f90-11e5-94b2-721aa616830c.png)
- [ ] NICE-TO-HAVE As time allows we'd be interested in doing that for the other breakpoints as well.

![screenshot 2015-12-10 22 54 37](https://cloud.githubusercontent.com/assets/15950066/11735611/0aaf4e58-9f91-11e5-979b-c87fcdfabe43.png)

![screenshot 2015-12-10 22 54 49](https://cloud.githubusercontent.com/assets/15950066/11735612/0f96efa2-9f91-11e5-99c4-defe0d6c84fd.png)

Horizontal and vertical logo files are in our shared Dropbox.

**Comment by halfempty** [comment]
@nikkichung @Dungjai Question about the transition between, let's call them, the "expanded" and "pinned" versions of the top. Couple of options...
1. The Expanded nav is simply placed on the top of the page. When you scroll down past it, the "pinned" version appears.
2. The Expanded nav is itself pinned, and when you scroll down the elements inside it compress and are redrawn.

Do those make sense? I'm thinking no. 1 is probably what we want?

**Comment by halfempty** [comment]
@nikkichung @Dungjai Also, do you want this "expanded" nav to happen in all situations, including article pages? (I remember having a conversation about it being only on the homepage or something?)

**Comment by nikkichung** [comment]
@halfempty We're pretty open on this one. If #1 is easier to produce let's do that. Let's stick with the expanded nav on the home page only.  If that feels strange to you, we can look at alternatives.

**Comment by nikkichung** [comment]
@halfempty One snag as we're seeing it come together: what happens to the nav links as the logo scrolls by?

<img width="1552" alt="screenshot 2016-01-03 15 55 26" src="https://cloud.githubusercontent.com/assets/15950066/12081579/9a86a310-b232-11e5-9d1d-b1350a0dc613.png">
<img width="1552" alt="screenshot 2016-01-03 15 55 35" src="https://cloud.githubusercontent.com/assets/15950066/12081591/0ca915c2-b233-11e5-9d92-0dc517ff9c89.png">
<img width="1552" alt="screenshot 2016-01-03 15 55 39" src="https://cloud.githubusercontent.com/assets/15950066/12081580/9aa63ed2-b232-11e5-9058-6d268dde0bdc.png">

Do you have a vision for what happens in that middle state?

**Comment by nikkichung** [comment]
@halfempty Expanded mobile nav comps are now in Dropbox https://www.dropbox.com/sh/jaq4ggoqxltde7r/AACpY3dBZ9gA7nmIv3Y9aGXea?dl=0
