### ISSUE TITLE
Essentials page

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#16]
@halfempty How do we create an Essentials page (a curated selection of necessary-read posts)? Should Essentials be a category? A tag? Something else?

**Comment by halfempty** [comment]
@nikkichung Either a category or tag could be used, and either would be fine from my perspective. The categories are what drive those red boxes at the top of the article, so if we used one of those it would show up there. Maybe that's cool? Maybe not cool? Tags, of course, display at the bottom.

**Comment by nikkichung** [comment]
@halfempty Good to know. We have a meeting with the client tomorrow so will bring this up with them and get a decision.

**Comment by nikkichung** [comment]
@halfempty Confirmed that tags is the right fit. It's possible we'll disable the page at launch until they have enough posts to fill the page, but I think we should build the functionality.
- 'Essentials' is not confirmed as the right name for the tag. Can we build it as that and change the name later? Or does the name need to be locked down first?

**Comment by halfempty** [comment]
@nikkichung Re: "Essentials" and the nav generally. When you get a chance, please navigate to Dashboard -> Appearance -> Menus and check out the editing interface there. It's where you & the client will be able to manage the items in the nav. Does it all make sense? 

Note that if you don't see "Tags", open the "Screen Options" tab and enable it.

**Comment by nikkichung** [comment]
@halfempty Got it!
