### ISSUE TITLE
Byline: Shuffling order of authors

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#17]
Client has requested the ability to control which author is listed first when a post has multiple authors. Is this functionality that needs to be added, or is this available already?

**Comment by halfempty** [comment]
@nikkichung We don't have this now. It would entail adding a new widget to the edit screen, and then re-building the Author bits to be controlled by the new widget. Would take some time-- 2/3 hrs maybe.

**Comment by Dungjai** [comment]
@halfempty we'll discuss how important this is to the client. @nikkichung do you know if this is a must-have?

**Comment by nikkichung** [comment]
@halfempty @Dungjai No priority assigned yet. We'll discuss this with the client tomorrow and get one.

**Comment by nikkichung** [comment]
@halfempty What would it take to set up listing the authors in alphabetical order by last name (currently it's by first name)? Client agrees that the manual shuffling widget is lower priority than other features.
