### ISSUE TITLE
Footer: social icons and links added

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#19]
- [x] Page links needed
- [x] Social media icons and RSS needed

Twitter: https://twitter.com/CommEdgeCollab
Instram: https://www.instagram.com/CommEdgeCollab/
Facebook: https://www.facebook.com/commonedge

**Comment by halfempty** [comment]
@nikkichung Okay, these are in. I tracked as closely to the comps as I could while still keeping the implementation simple. When we return to do more on the footer, we can put more time towards these as well.
