### ISSUE TITLE
Q&A Formatting

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#20]
- [x] Indenting alignment is just slightly off at beginning of question:

![img_8422](https://cloud.githubusercontent.com/assets/15950066/11603037/de8f72dc-9aac-11e5-8a25-6de99299590b.PNG)

**Comment by nikkichung** [comment]
@halfempty Client has zero knowledge of CSS. How might we make post formatting for Q&As available in the Wordpress editor?

**Comment by halfempty** [comment]
Fixed
