### ISSUE TITLE
Pull-quote indent

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#23]
- [x] Please make the pull-quote indent 2x the paragraph indent at all sizes

**Comment by halfempty** [comment]
@nikkichung Okay done. However, I set it at 1x the paragraph indent at the smallest sizes (phone), 'cause the lines were so short it affected readability. Cool?

**Comment by nikkichung** [comment]
@halfempty :( I misjudged this one. Pull quotes are better at 1x paragraph indent at all sizes. If it's possible to revert without pain, could we do so?

**Comment by halfempty** [comment]
Done!
