### ISSUE TITLE
Article: Link style needed for body text

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#25]
@halfempty Linked text isn't apparent in the body of posts. Could you turn the text red when there's a link?

<img width="1549" alt="screenshot 2015-12-21 18 39 33" src="https://cloud.githubusercontent.com/assets/15950066/11945158/57cef07e-a812-11e5-8111-a1c210339c8f.png">
<img width="1549" alt="screenshot 2015-12-21 18 39 42" src="https://cloud.githubusercontent.com/assets/15950066/11945159/57d33d78-a812-11e5-98ea-18104809eae5.png">

**Comment by halfempty** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/775543/12249081/29a08cae-b883-11e5-8ed8-ee75c0dd9d6e.png)
