### ISSUE TITLE
Post formatting issues

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#26]
@halfempty We're having trouble styling posts. My pre-vacation brain remembers being able to do more styling via the Wordpress editor (block quotes and Q&A styling, for example). Do these things now have to be done with CSS tags?

**Comment by halfempty** [comment]
@nikkichung The Q&A stuff all involves tags & classes. Is that what you mean?

**Comment by nikkichung** [comment]
@halfempty Ahh I see. Bummer, the client isn't capable of using CSS. How about pull-quotes? I was digging through a few published posts, where I remember using the block-quote button, but that no longer works. 

Any options for making the styling available in the editor or simplifying workflow for someone who doesn't know CSS?
