### ISSUE TITLE
Landing page : First post styling

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#27]
@halfempty A few requests on the styling of the first post of the landing page:
![screenshot 2016-01-07 13 55 22](https://cloud.githubusercontent.com/assets/15950066/12179830/119743bc-b547-11e5-831c-8a7648d08f5b.png)
- [x] Please make the post title (h3?) Boutique, matched to size and style of the articles pages. 
- [x] Would like first post title, category, byline, etc. to appear a little higher (this might resolve automatically with the new post title style)
- [x] Reduce size of Common Edge logo slightly (so things feel a little more fluid/less boxy)

**Comment by halfempty** [comment]
@nikkichung Done.

![image](https://cloud.githubusercontent.com/assets/775543/12249025/def77d3e-b882-11e5-8494-ddcf427c872f.png)
