### ISSUE TITLE
Change typeface on Landing pg first post

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#29]
@halfempty
![screenshot 2016-01-07 13 55 22](https://cloud.githubusercontent.com/assets/15950066/12179830/119743bc-b547-11e5-831c-8a7648d08f5b.png)
- [x] Please make the first post title (h3?) Boutique, matched to size and style of the articles pages (current typeface is Founders Grotesk)

**Comment by halfempty** [comment]
@nikkichung Of course! I looked right past that. Okay, better now?

**Comment by nikkichung** [comment]
👌
