### ISSUE TITLE
Authors needs work

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#3]
The "Authors" bit isn't 100% finished..

_The author bios at the bottom:_
- [x] Small thing. Add the author's name (clickable) before the bio itself.
- [x] Larger thing. Only the first author's bio is displaying.

**Comment by halfempty** [comment]
- [x] Also, Author headshots.

**Comment by halfempty** [comment]
- [x] Author archives not working yet

**Comment by halfempty** [comment]
- [ ] It would be ideal to pluralize the "Author Bio" line, but only when necessary

**Comment by nikkichung** [comment]
@halfempty Can you weed out things that are no longer needed here? I'm not sure what the remaining checkboxes are.

**Comment by halfempty** [comment]
It's these two:
- [ ] It would be ideal to pluralize the "Author Bio" line, but only when necessary
- [ ] Small thing. There's no "and" before the last name. Just a comma.

& if they're not important to y'all, we can nix them.
