### ISSUE TITLE
Fine-tuning styles

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#30]
@halfempty 
### 1024px
- [x] Line-height of the body text is a bit tight. In Chrome, 1.58em feels pretty good.
- [x] Body text size looks a bit large. Could we come down to 16px?

**Current:**
![screenshot 2015-12-08 22 13 08](https://cloud.githubusercontent.com/assets/15950066/11735924/1a9d93e8-9f95-11e5-9c53-57a90acdf55f.png)

**Preferred:** 
![screenshot 2015-12-08 22 26 54](https://cloud.githubusercontent.com/assets/15950066/11735932/4990a3d4-9f95-11e5-925a-f04a21989d3b.png)
- [x] Landing pg h3 could use a bit more line-height to keep certain letters from touching (see 'George' and 'of'):

<img width="811" alt="screenshot 2016-01-27 21 45 00" src="https://cloud.githubusercontent.com/assets/15950066/12633461/1b4ae91e-c540-11e5-83d1-d2e37c53c6bc.png">

~~\- [ ] Could you wrap the title at a shorter column width than the rule?~~
- [x] Please increase distance between main content and footer.

![screenshot 2015-12-08 23 49 06](https://cloud.githubusercontent.com/assets/15950066/11735958/80133ce6-9f95-11e5-891f-f3a1af86cf98.png)
##### Tags, Author Bio
- [x] lay out horizontally rather than vertical stack to keep those rules from being so long.
  ![screenshot 2015-12-08 22 46 53](https://cloud.githubusercontent.com/assets/15950066/11735957/7a21d84c-9f95-11e5-8a7a-9554fa405d2d.png)
- [x] Increase margin/padding between these sections
### 768px
- [ ] The rules at the footer—Share This Story, Tags—should match the length of the rule above the byline.
- [x] Please increase distance between main content and footer

**Comment by halfempty** [comment]
@nikkichung Okay, I've looked at these. One thing-- I was able to get all the bottom lines to line-up with eachother, but having them line up with the byline at the top was turning into a bit of a quagmire. It has to do with things being nested into different divs, some of which have max-widths and some not. So I'm going to leave it as-is for now, and if it really bugs you I can come back to it!

**Comment by halfempty** [comment]
@nikkichung Ps. Am closing this issue, and we can open a new one for that one bit, if needed.
