### ISSUE TITLE
Wrapping Author By-Line

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#33]
### 768px, 480px, and 320px
- [x] Once author byline starts running into date, could we move the byline to be flush-left? Alternately, can we wrap the text of the author byline so the names stack rather than running under the date?

**Current**

![img_1183](https://cloud.githubusercontent.com/assets/15950066/11736424/382b6da2-9f9c-11e5-8b90-f8c2829fef97.jpg)

**Preferred**

![screenshot 2015-12-11 00 19 02](https://cloud.githubusercontent.com/assets/15950066/11736472/d5d82b6c-9f9c-11e5-9801-dd99ece9cb86.png)

or

![screenshot 2015-12-11 00 19 10](https://cloud.githubusercontent.com/assets/15950066/11736477/da6d0d6e-9f9c-11e5-8a5b-bc0cfb7d1bb7.png)

**Comment by halfempty** [comment]
@nikkichung What I've done here is applied the `float: right` only on the article page, and only at the larger sizes. In other cases (index template + small size article), the names are underneath.

**Comment by nikkichung** [comment]
It's great!
