### ISSUE TITLE
Index Template: Image sizes

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#34]
@halfempty 
- [x] Could you try an image aspect ratio like 1:1.6 so images are less tall?
- [ ] Can we set a maximum width for the images at 1024px+ breakpoint? (We're not confident the client will be sourcing attractive images until they can hire a photo editor, so would like to keep images a bit smaller. Something around here: 

![screenshot 2015-12-08 22 54 04](https://cloud.githubusercontent.com/assets/15950066/11736369/6173980c-9f9b-11e5-93a9-bc4dbd632113.png)

**Comment by halfempty** [comment]
@nikkichung Okay, I've done the first part of this, which is image ratios.

The second part isn't as simple, though. When I set a max-width, this happens:

![image](https://cloud.githubusercontent.com/assets/775543/12628486/0dc2d626-c509-11e5-9e22-6bfaca417b04.png)

I'll require a bunch of rework & tweaking to get it right. What do you think?

**Comment by nikkichung** [comment]
@halfempty Oh darn. OK let's discuss when we chat tomorrow.

**Comment by halfempty** [comment]
@nikkichung Okay, this is in

**Comment by nikkichung** [comment]
:heart:
