### ISSUE TITLE
Mobile Nav needed

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#35]
@halfempty Expanded mobile nav comps are in Dropbox https://www.dropbox.com/sh/jaq4ggoqxltde7r/AACpY3dBZ9gA7nmIv3Y9aGXea?dl=0

**Comment by halfempty** [comment]
@nikkichung Did some work on this. I got the "fixed" version completely in. (This is what shows on interior pages, and when you're scrolled down on the homepage.) 

But when I got to doing the version at the top of the homepage, I hit a snag. We don't have full illustration of this in the comps. I found examples of parts of it at some sizes, but haven't been able to piece together a comprehensive understanding. 

Specifically, where should I place the "open" version of the homepage-top nav and what does that look like?

Also with regards to the homepage-top, I wanted to ask about placement of the hamburger. If we place it on the left, as the comps show, we'll need to push over the logo a bit on that side. Which is fine. But we might want to consider placing it on the right, where we've got that white space.  It would affect placement of the eventual search icon, but that could be resolved, potentially.

I've put that in place, so you can see it. (And put it there for the fixed nav as well, for consistency.) Let me know what you prefer. Thanks!

**Comment by nikkichung** [comment]
@halfempty Taking a look now, but I don't think I understand the first part of the issue. Are you around this afternoon? I can Skype you quickly to solve this.

**Comment by halfempty** [comment]
@nikkichung Sure, give me a call whenever works for you!

**Comment by halfempty** [comment]
@nikkichung Okay, the changes we discussed yesterday are in. Going to close this issue; please reopen if needed.

**Comment by nikkichung** [comment]
@halfempty It's fabulous! Thank you!
