### ISSUE TITLE
Advanced Custom Fields plug-in added

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#37]
@halfempty Client cannot/will not use CSS, so let's add this plug-in to handle any formatting that previously required CSS (pull-quotes, drop-caps, Q&A, etc.)

**Comment by halfempty** [comment]
@nikkichung For pull-quotes, I had been using the tag `<aside>`, but there's no option in the toolbar for that. So instead, let's use `<blockquote>` to do the pull-quotes:

![image](https://cloud.githubusercontent.com/assets/775543/12459156/f427f836-bf72-11e5-9acf-759fc224565d.png)

Looks like this:

![image](https://cloud.githubusercontent.com/assets/775543/12459170/05172df6-bf73-11e5-8ac2-19cab96e2193.png)

**Comment by nikkichung** [comment]
Sounds good!
http://once-future.com

On Wed, Jan 20, 2016 at 1:41 PM, Marty Spellerberg <notifications@github.com

**Comment by halfempty** [comment]
@nikkichung I've converted the Q&A to "custom fields", an example here:

http://commonedge.staging.wpengine.com/katrina-10-its-engaged-citizens-who-saved-new-orleans/

If you click "Edit" you can see the editing interface. You can also create a new post to check out how it looks before filling it in. Will this work for the client, do you think?

**Comment by halfempty** [comment]
@nikkichung The drop-caps are now handled by JavaScript, which automatically finds the first letter in a post and wraps it in a `<span>`:

![image](https://cloud.githubusercontent.com/assets/775543/12465321/0d84138a-bf93-11e5-9455-f319298205d6.png)

With that, I _think_ we've covered all the places where we were using special classes and such. Did I miss any?

**Comment by nikkichung** [comment]
@halfempty Thanks! 

For the Q&A, we're going to send it over to the client to try. At first pass it seemed a bit cumbersome, but let's see what happens. Is there a back-up plan if this is too much for them?

For the drop-caps, this is a good solution for clients who need as much automated as possible. We'll ask the client to avoid opening with two-letter words or contractions. 

For pull-quotes, `<blockquote>` is perfect—nice and easy. 

I think you got everything!
