### ISSUE TITLE
Banner Image height reduced

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#38]
@halfempty Need to reduce the height of the banner images in posts so that post titles are at least partially visible above the fold. 

Current: 
![screenshot 2016-01-12 15 38 17](https://cloud.githubusercontent.com/assets/15950066/12276224/a838cc4c-b942-11e5-9394-3648529beefc.png)

Preferred: 
![screenshot 2016-01-12 15 40 18](https://cloud.githubusercontent.com/assets/15950066/12276254/d60f1af4-b942-11e5-8cd6-76a9a73490f0.png)

**Comment by halfempty** [comment]
@nikkichung Okay, this is in. Pls take a look:

http://commonedge.staging.wpengine.com/blair-kamin-on-the-chicago-biennial-george-lucas-and-the-magic-of-jeanne-gang/

**Comment by nikkichung** [comment]
Yay! :raised_hands:
