### ISSUE TITLE
WP Engine Billing

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#40]
@nikkichung We need to move this off my credit card

**Comment by nikkichung** [comment]
@halfempty Oh yes, good call. I'll track down client cc info.

**Comment by nikkichung** [comment]
@halfempty Following up on this. What's easier for you: 
1. We provide you with client's cc info?
2. You provide us with instructions on how to update the cc on the account.

**Comment by nikkichung** [comment]
Changed CC info, and added client as owner.
