### ISSUE TITLE
Need to be able to add media to body of Q&A

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#41]
@halfempty Potential bug: it doesn't seem possible to add an image/video to the body of a Q&A. Using the 'Add Media' button automatically places the image and caption in the top text box. We'll need a way to add it further down the page without CSS.

Attempts to cut/paste resulted in caption formatting being lost.

**Comment by halfempty** [comment]
@nikkichung Okay, I've added the ability to add images and embeds (such as video). Now, when you click "Add Block" the options are Text, Image or Embed blocks.
