### ISSUE TITLE
Switch position of Tags and Author Bio

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#48]
@halfempty We'd like Author Bio and Tags to switch positions. 

Current:

![screenshot 2016-02-02 15 30 51](https://cloud.githubusercontent.com/assets/15950066/12763371/09862cee-c9c2-11e5-8a57-2118375cb744.png)

Preferred:

![screenshot 2016-02-02 15 31 54](https://cloud.githubusercontent.com/assets/15950066/12763389/1e2f914e-c9c2-11e5-86e4-e860903fa55f.png)

**Comment by halfempty** [comment]
@nikkichung Tags and author placement switched

**Comment by nikkichung** [comment]
Thank you!
