### ISSUE TITLE
Q&A Markup

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#5]
I've styled the Q&A example. Please let me know if it's how you envisioned it:

http://commonedge.staging.wpengine.com/katrina-10-its-engaged-citizens-who-saved-new-orleans/

I should point-out that even through I tried to keep it as simple as possible, I doubt the client will have the appitite to put in all the markup required to get the formatting this way.

We may need to come back to this.

**Comment by halfempty** [comment]
**Nikki said:**
- [ ] Possible to indent the first line of a second paragraph within a Q&A question or response, rather than a line break?
- [x] Could we make the Q&A ‘speaker’ text color the tan/brown instead of red?

![image](https://cloud.githubusercontent.com/assets/775543/11520506/ac4d1346-9869-11e5-8aa1-178608ee5fe0.png)

**Comment by halfempty** [comment]
> How do we control dropcaps—one vs two letters? Does this have to be done in the HTML editor?

Yes, the markup for all of this needs to be done in the HTML editor. I can see the client having trouble with this. We should discuss it.

**Comment by nikkichung** [comment]
> I've styled the Q&A example. Please let me know if it's how you envisioned it:
> 
> http://commonedge.staging.wpengine.com/katrina-10-its-engaged-citizens-who-saved-new-orleans/
> 
> I should point-out that even through I tried to keep it as simple as possible, I doubt the client will have the appitite to put in all the markup required to get the formatting this way.

Good point. I agree. So far they haven't visibly tinkered with Wordpress, but we've given a tutorial and have fingers crossed that they'll dive in soon. They can always copy and paste...?

> Yes, the markup for all of this needs to be done in the HTML editor. I can see the client having trouble with this. We should discuss it.

Open to suggestions here. Worst case scenario, they don't use them, which would be sad for us designers, but not for anyone else who didn't know they existed.

**Comment by halfempty** [comment]
@nikkichung,

> Possible to indent the first line of a second paragraph within a Q&A question or response, rather than a line break?

Actually, this gets really gnarly. I gave it a try, but it was turning into multiple lines of conditional statements and overrides in the CSS. It was getting to be a real mess. To do it properly we'll need even more HTML in the body than we already have.

**Comment by nikkichung** [comment]
Alright, let's shelve it. Thanks for trying!

http://once-future.com

**Comment by halfempty** [comment]
@nikkichung Okay, I'll just close this, then
