### ISSUE TITLE
Landing page: Newsletter and Donation alignment

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#51]
@halfempty Landing page width is looking awesome! Thanks for updating it. Looks like the Newsletter and Donation became misaligned in the process. Could you align them with the main column?

Current:
![screenshot 2016-02-02 15 21 54](https://cloud.githubusercontent.com/assets/15950066/12764253/a21e9ab4-c9c6-11e5-9fd6-0d7f6e1043c0.png)

Preferred (but with strokes flush at left and right):
![screenshot 2016-02-02 16 04 56](https://cloud.githubusercontent.com/assets/15950066/12764275/c46e6a54-c9c6-11e5-98cd-07d04454a2ee.png)

**Comment by halfempty** [comment]
@nikkichung Okay, I think this is in.

**Comment by nikkichung** [comment]
:+1:
