### ISSUE TITLE
Sharing posts on FB: Feature Image doesn't always appear

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#52]
@halfempty Client is finding that the featured image only appears in Facebook occasionally. Thoughts on why this is happening?

https://www.facebook.com/commonedge/?fref=ts

**Comment by halfempty** [comment]
@nikkichung There are some Facebook-specific meta tags we can add. In addition to the image, I'd want to make sure it picks up the correct author names as well.

**Comment by nikkichung** [comment]
@halfempty OK cool. Can you give us a time estimate? I'll see about getting funding for enhancements/maintenance.

**Comment by halfempty** [comment]
@nikkichung Maybe three hours?

**Comment by nikkichung** [comment]
@halfempty Thanks for the estimate. I'll be in touch once we get a maintenance budget in place.

**Comment by nikkichung** [comment]
@halfempty Maintenance approved. Client has opted for as-we-go maintenance rather than budgeting for an anticipated number of hours each month. I find this strategy a bit shortsighted, so please keep me posted if we think things will go over estimate. Plan to bill monthly.

Could you carve out some time to address this issue this week? They are eager to get this updated.

**Comment by halfempty** [comment]
@nikkichung Okay, these are in. I'm finding FB's parser to be slightly ... flakey? ... but we're now supplying the tags it wants, including specifying a feature image of appropriate specifications.
