### ISSUE TITLE
Title/menu overlap

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#54]
@nikkichung This is happening...

![image](https://cloud.githubusercontent.com/assets/775543/13273745/6d938dda-da6b-11e5-9d0a-e1ab0690c0ed.png)

Not sure how we didn't catch it before?
How'd you like to fix it?

**Comment by nikkichung** [comment]
@halfempty Can we shrink the logo at the smallest breakpoint?

**Comment by halfempty** [comment]
@nikkichung What if I shrink it slightly and left-align?

**Comment by nikkichung** [comment]
Sounds good!

On Thu, Feb 25, 2016 at 1:40 PM, Marty Spellerberg <notifications@github.com

**Comment by halfempty** [comment]
@nikkichung okay, done!

![image](https://cloud.githubusercontent.com/assets/775543/13330379/43907f62-dbbe-11e5-9a86-10289ad8e7fd.png)

**Comment by nikkichung** [comment]
Thank you!
http://once-future.com

On Thu, Feb 25, 2016 at 1:50 PM, Marty Spellerberg <notifications@github.com
