### ISSUE TITLE
RSS feed in Chrome

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#56]
@halfempty Is it normal for clicking the RSS icon to result in a page of code (happens in Chrome)?

![screenshot 2016-03-29 15 01 18](https://cloud.githubusercontent.com/assets/15950066/14120059/3629f55e-f5bf-11e5-82b0-0760dcd82be2.png)

In Firefox users are given a prompt to subscribe with their preferred reader. 
![screenshot 2016-03-29 15 02 44](https://cloud.githubusercontent.com/assets/15950066/14120108/60521514-f5bf-11e5-8bbd-0aa65ea092b0.png)

**Comment by halfempty** [comment]
@nikkichung yes, it's normal (unfortunately). There are extensions that render feeds, but that's the default behavior

**Comment by nikkichung** [comment]
@halfempty OK no probs, as long as it's not broken we won't fix it. Let's file the addition of an extension as a future feature request.
