### ISSUE TITLE
Spam comments

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#59]
@halfempty We're starting to get email notifications about spam comments. Anything we should do to limit or get rid of these?

https://www.dropbox.com/s/umybct4cuky7q4x/Screenshot%202016-05-26%2012.13.32.png?dl=0

**Comment by halfempty** [comment]
@nikkichung They're trackbacks, rather than comments exactly. Which is why, I think, the spam-catcher Askimet isn't catching them.

It's possible to disable them altogether. Would you like me to?

**Comment by nikkichung** [comment]
I have no idea what a trackback is, so the client probably doesn't either.
If you think it's good to disable them let's do it. Thanks!

Nikki Chung
Once–Future Office
+1 917 524 8187
http://once-future.com

On Thu, May 26, 2016 at 1:43 PM, Marty Spellerberg <notifications@github.com

**Comment by halfempty** [comment]
@nikkichung Okay, I've disabled them via some settings WP makes available. Hopefully this'll help.

(Trackbacks are where one blog links to another and then sends them a notification of that. It's a convention from the early days of blogging, to enable conversations to happen across multiple sites. But spammers abused them and ruined them for everyone. IMO WordPress should remove them from the core software and make them optional.)

**Comment by nikkichung** [comment]
Thanks Marty!

On Thu, May 26, 2016 at 1:56 PM, Marty Spellerberg <notifications@github.com
