### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#6]
Make a temporary splash page with C/E logo

**Comment by halfempty** [comment]
Okay, this is done:

http://commonedge.org/

**Comment by nikkichung** [comment]
Client request: 
- [ ] Text should read 'Under Construction'

**Comment by halfempty** [comment]
@nikkichung Will you make me a new graphic, with spacing & type exactly how you'd like it?

**Comment by nikkichung** [comment]
Sure! One moment...

**Comment by nikkichung** [comment]
![commonedge_underconstruction](https://cloud.githubusercontent.com/assets/15950066/11602029/465cc6e2-9aa5-11e5-8220-e9914fb06f8b.png)
@halfempty Here's a new image (I'll put the design file in Dropbox too)

**Comment by halfempty** [comment]
Okay, it's in. (Refresh your cache to see it, probably)

http://commonedge.org/

**Comment by nikkichung** [comment]
Boom. Done!
