### ISSUE TITLE
Social share icons not showing

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#61]
Hey @halfempty,

Hope you're well. We're experiencing a bug where the social share icons on posts aren't showing up. Screenshot:

https://www.dropbox.com/s/aq8wmd9xb2t1ooy/Screenshot%202017-11-10%2012.35.55.png?dl=0

Thanks!

**Comment by halfempty** [comment]
Hi @nikkichung! Sorry for the delayed response.

What's happened is that the font that is serving those icons has changed. If you go to Appearance -> Genericon'd, that's where things are at. We were using "Genericon'd Classic" which, as you'll see, is now greyed-out / unavailable.

The CSS needs to be updated to support the new "Social Logos" font set. I tried to pop in and do it quickly, but it appears I no longer have the password.

**Comment by nikkichung** [comment]
Thanks Marty.

Here's a new password for you:
sq683*Fxj@WeEx3OUfMa^w6p

**Comment by halfempty** [comment]
@nikkichung Oh! Reminder-- Don't post passwords in GitHub issues! They're public!

Also, I should have specified, I meant FTP password.

**Comment by nikkichung** [comment]
Oops!

**Comment by nikkichung** [comment]
Hmmm... I'm having trouble finding that too. Can it be accessed via
WPEngine?

Nikki Chung
Once–Future Office
917 524 8187
once-future.com

**Comment by halfempty** [comment]
@nikkichung I've got this going...

![image](https://user-images.githubusercontent.com/775543/33036369-c287e66a-cdf3-11e7-8f59-c07a628b0de3.png)

What do you think? If you want to tweak the icons, could you send me new SVGs?

**Comment by nikkichung** [comment]
Hey Marty,

Sorry for the slow response! I'm scrambling to finish things before I leave
on vacation tonight. New Facebook SVG is here (others look good!):
https://www.dropbox.com/s/vuosynk168sv5at/facebook.svg?dl=0


On Mon, Nov 20, 2017 at 2:08 PM, Marty Spellerberg <notifications@github.com

**Comment by halfempty** [comment]
@nikkichung okay done

**Comment by nikkichung** [comment]
Thank you!

**Comment by nikkichung** [comment]
Ack, I've been informed this is happening in the footer
<https://www.dropbox.com/s/rnzle1zxp052j9j/Screenshot%202017-11-27%2017.30.16.png?dl=0>
as well. Could you update?

Thanks and hope you had a splendid Thanksgiving.

**Comment by halfempty** [comment]
@nikkichung ok fixed!

**Comment by nikkichung** [comment]
Wonderful, thank you!
