### ISSUE TITLE
Article Text Size Tweaks

### ISSUE THREAD

**Issue by halfempty** [once-future/commonedge#7]
**Nikki said:**
- [x] All text is reading a bit small. Could you scale things up by about 2pts?
- [x] Make photo captions 1–2px smaller than the body text size. 
- [x] Increase the top and bottom margin (padding?) around in-line images a bit (try matching to that of the pull-quotes)
- [x] Increase line-height of post-categories h2 so the text isn't colliding ('Engaged' and 'Who'). In Chrome I found 1.08em was a good amt. 

![screenshot 2015-12-03 15 13 06](https://cloud.githubusercontent.com/assets/15950066/11572663/60a82b52-99d0-11e5-97b6-1d3503a86d0e.png)

**Comment by halfempty** [comment]
These changes are in.

**Comment by nikkichung** [comment]
:+1: Thanks!
