### ISSUE TITLE
About pg

### ISSUE THREAD

**Issue by nikkichung** [once-future/commonedge#8]
@halfempty Packaged INDD files of the About page are in our shared Dropbox: https://www.dropbox.com/sh/1f27bcwob6irw7f/AAAKtirgsFsSnkZwzNAqKqEfa?dl=0

**Comment by halfempty** [comment]
@nikkichung In-progress:

http://commonedge.staging.wpengine.com/about/

In the comp I'm seeing a different amount of padding under the headline here vs. on post. Would it be possible to keep it the same across both?

**Comment by nikkichung** [comment]
Thanks for catching that. Yes, let's leave it consistent. If time allows we
can make a global change during enhancements.

**Comment by halfempty** [comment]
@nikkichung I'll close this one. Re-open if needed.
